/**
 * WS2 Effect Envelope — the unified contract for every external side effect
 * admitted by the EffectBroker.
 *
 * This module is the single cross-plane contract type for effects. It is
 * imported by @praetor/effect-broker (PEP), @praetor/kernel (durable
 * ledger + `ops/compensationConsumer` library), and @praetor/worker-plane
 * (callers). The former `@praetor/operations` plane was folded into
 * kernel-ops (WS1) and must not reappear. An L4-B follow-up may add deploy
 * unit `@praetor/adapter-ops` for production compensation drain (absent on
 * master). No ad-hoc effect shape may cross a plane boundary.
 *
 * Invariants (enforced by the broker at admit time):
 *   1. The four identity fields (effect_id, tenant_id, run_id, step_id) are
 *      non-empty and match `^[A-Za-z0-9_-]{1,128}$`.
 *   2. idempotency_key is recomputed by the broker and compared against the
 *      caller-supplied value; mismatch ⇒ REJECTED.
 *   3. status is only written by the broker and the kernel; callers read only.
 */

/**
 * Status of an effect in the broker/kernel ledger.
 *
 * - `admitted`:    admit() succeeded; effect is durable in the kernel ledger.
 * - `executing`:   execute() has dispatched the effect to the executor.
 * - `completed`:   executor returned and kernel.completeEffect() committed.
 * - `failed`:      executor threw or completion was rejected.
 * - `rejected`:    admit() denied the effect (policy/capability/quota/...).
 * - `replayed`:    idempotency key hit an already-completed effect.
 */
export type EffectEnvelopeStatus =
  'admitted' | 'executing' | 'completed' | 'failed' | 'rejected' | 'replayed';

/**
 * Action namespace enum. Actions are dotted strings; the first segment is the
 * namespace. The broker uses the namespace to route to executors and to apply
 * allowlist/rate-limit/quota policy by class.
 *
 * - `http.*`:        outbound HTTP/gRPC calls.
 * - `llm.*`:         LLM provider API calls (completions, embeddings, ...).
 * - `connector.*`:   managed connector operations (Slack, GitHub, DB, ...).
 * - `compensate.*`:  compensation (reverse) effects emitted by the outbox.
 * - `tool.*`:        generic tool invocations that touch external state.
 */
export const EFFECT_ACTION_NAMESPACES = ['http', 'llm', 'connector', 'compensate', 'tool'] as const;

export type EffectActionNamespace = (typeof EFFECT_ACTION_NAMESPACES)[number];

/**
 * Unified effect envelope. All fields use snake_case to match the kernel
 * Postgres schema (commander_effects) and the outbox payload shape; the
 * contracts package keeps this naming convention for cross-plane stability.
 */
export interface EffectEnvelope {
  /** Globally unique effect ID (UUID v4). Generated by the caller or broker. */
  effect_id: string;
  /** Tenant ID. Must match the capability token's tenantId. */
  tenant_id: string;
  /** Run ID. References kernel runs table. */
  run_id: string;
  /** Step ID. References kernel steps table. */
  step_id: string;
  /** Action type, e.g. "http.post" | "llm.complete" | "connector.slack.postMessage" | "compensate.http.delete". */
  action: string;
  /** Action payload. Structure is determined by `action`; the executor parses it. */
  payload: Record<string, unknown>;
  /**
   * Idempotency key. Caller-supplied; broker recomputes
   * SHA-256(run_id + step_id + action + canonical(payload)) and rejects
   * mismatches. Same key ⇒ broker returns cached response.
   */
  idempotency_key: string;
  /** Written by broker/kernel only. Callers must not set this on admit(). */
  status: EffectEnvelopeStatus;
}

/** Extract the namespace (first dotted segment) of an action string. */
export function actionNamespace(action: string): EffectActionNamespace | null {
  const idx = action.indexOf('.');
  const head = idx === -1 ? action : action.slice(0, idx);
  return (EFFECT_ACTION_NAMESPACES as readonly string[]).includes(head)
    ? (head as EffectActionNamespace)
    : null;
}

/** Identity-field charset. Used by the broker to validate envelope fields. */
export const EFFECT_ID_PATTERN = /^[A-Za-z0-9_-]{1,128}$/;

/**
 * Validate the four identity fields of an envelope. Returns true iff all are
 * non-empty and match the allowed charset. Does NOT validate idempotency_key
 * (the broker recomputes it) or status (broker/kernel-owned).
 */
export function isValidEffectEnvelopeIdentity(envelope: {
  effect_id: string;
  tenant_id: string;
  run_id: string;
  step_id: string;
}): boolean {
  return (
    EFFECT_ID_PATTERN.test(envelope.effect_id) &&
    EFFECT_ID_PATTERN.test(envelope.tenant_id) &&
    EFFECT_ID_PATTERN.test(envelope.run_id) &&
    EFFECT_ID_PATTERN.test(envelope.step_id)
  );
}

// ---------------------------------------------------------------------------
// Governed Action Gateway V1
// ---------------------------------------------------------------------------

export const ACTION_STATES_V1 = [
  'PROPOSED',
  'AWAITING_APPROVAL',
  'ADMITTED',
  'RUNNING',
  'SUCCEEDED',
  'FAILED',
  'COMPLETION_UNKNOWN',
  'ESCALATED',
] as const;

export type ActionStateV1 = (typeof ACTION_STATES_V1)[number];
export type ActionEffectV1 = 'allow' | 'deny' | 'require_approval';

export interface ActionProposeRequestV1 {
  source: string;
  package: string;
  model: string;
  tool: string;
  destination: string;
  effectType: string;
  args: Record<string, unknown>;
  idempotencyKey: string;
}

export interface ActionDecisionV1 {
  effect: ActionEffectV1;
  decisionId: string;
  reason: string;
  policySnapshotId: string;
}

export interface ActionSimulationV1 extends ActionDecisionV1 {
  simulationId: string;
  actionDigest: string;
}

export interface GovernedActionV1 {
  runId: string;
  stepId: string;
  effectId: string;
  state: ActionStateV1;
  decision: ActionDecisionV1;
  simulation: ActionSimulationV1;
  actionDigest: string;
  policySnapshotId: string;
  createdAt: string;
  updatedAt: string;
}

export interface ActionApprovalRequestV1 {
  actionDigest: string;
  simulationId: string;
  policySnapshotId: string;
}

export interface ActionCompensationRequestV1 {
  originalEffectId: string;
  adapterVersion: string;
  compensationEffectType: string;
  compensationPatch: Record<string, unknown>;
  forwardReceiptHash: string;
}

export interface ActionCompensationApprovalRequestV1 {
  actionDigest: string;
  policySnapshotId: string;
}

export interface ActionCompensationAuthorizationV1 {
  id: string;
  tenantId: string;
  originalRunId: string;
  originalEffectId: string;
  compensationEffectType: string;
  adapterVersion: string;
  compensationPatch: Record<string, unknown>;
  forwardReceiptHash: string;
  policyDecisionId: string;
  policySnapshotId: string;
  decision: 'allow' | 'require_approval' | 'deny';
  actionDigest: string;
  expiresAt: string;
  approvalInteractionId?: string;
}

export interface ActionCompensationAwaitingApprovalV1 {
  authorization: ActionCompensationAuthorizationV1;
  replayed: boolean;
  state: 'AWAITING_APPROVAL';
}

export interface ActionCompensationRequestAcceptedV1 {
  accepted: true;
  request: Record<string, unknown>;
  replayed: boolean;
}

export type ActionCompensationRequestResponseV1 =
  ActionCompensationAwaitingApprovalV1 | ActionCompensationRequestAcceptedV1;

export interface ActionCompensationApprovalResponseV1 {
  interaction: Record<string, unknown>;
  accepted: true;
  request: Record<string, unknown>;
  replayed: boolean;
}

export interface ActionRejectionRequestV1 {
  reason?: string;
}

export interface ActionSimulationResponseV1 {
  simulation: ActionSimulationV1;
}

export interface ActionResponseV1 {
  action: GovernedActionV1;
}

export interface ActionProposeResponseV1 extends ActionResponseV1 {
  idempotentReplay: boolean;
}

export interface ActionReconcileAcceptedV1 {
  scheduled: true;
  effectId: string;
  state: 'COMPLETION_UNKNOWN';
  reconcileAfter: string;
  alreadyScheduled: boolean;
}

export interface ActionEvidenceSignatureV1 {
  algorithm: 'Ed25519';
  keyId: string;
  signedAt: string;
  value: string;
}

export interface ActionEvidenceEffectV1 {
  effectId: string;
  stepId: string;
  type: string;
  state: string;
  policyDecisionId: string;
  requestHash: string;
  approvalInteractionId?: string;
  responseSummary?: Record<string, unknown>;
  createdAt: string;
  completedAt?: string;
  entryHash: string;
  prevEntryHash: string;
}

export interface ActionEvidenceAuditEventV1 {
  type: string;
  at: string;
  severity: string;
  stepId?: string;
  details: Record<string, unknown>;
  entryHash: string;
  prevEntryHash: string;
}

export interface ActionEvidenceReceiptV1 {
  schemaVersion: 'l3-11.v0';
  bodyVersion: 'commander.evidence-body/v1';
  bundleId: string;
  exportedAt: string;
  actionDigest: string;
  terminalDisposition: 'SUCCEEDED' | 'FAILED' | 'ESCALATED';
  scope: {
    tenantId: string;
    runId: string;
    effectId?: string;
  };
  identity: {
    intentHash?: string;
    workGraphHash?: string;
    capabilityGrant?: {
      jti: string;
      issuer?: string;
      audience?: string;
      requestHash?: string;
      policySnapshotId?: string;
    };
  };
  versions: {
    policySnapshotId: string;
    workGraphVersion?: string;
    kernelApiVersion?: string;
  };
  effects: ActionEvidenceEffectV1[];
  auditEvents: ActionEvidenceAuditEventV1[];
  contentHash: string;
  signature: ActionEvidenceSignatureV1;
}

export interface ActionEvidenceVerificationV1 {
  ok: boolean;
  reason?: string;
  brokenAt?: 'effects' | 'auditEvents' | 'contentHash' | 'dlp';
  index?: number;
}

export interface ActionEvidenceV1 {
  receipt: ActionEvidenceReceiptV1;
  verification: ActionEvidenceVerificationV1;
}

export interface ActionErrorDetailV1 {
  code: string;
  message?: string;
  details?: unknown;
}

export interface ActionErrorV1 {
  error: ActionErrorDetailV1;
}

export const ACTION_KILL_SWITCH_SCOPES_V1 = [
  'tenant',
  'package',
  'model',
  'tool',
  'destination',
  'effect-type',
] as const;

export type ActionKillSwitchScopeV1 = (typeof ACTION_KILL_SWITCH_SCOPES_V1)[number];

export interface ActionKillSwitchV1 {
  tenantId: string;
  scope: ActionKillSwitchScopeV1;
  value: string;
  enabled: boolean;
  reason?: string;
  actor: string;
  updatedAt: string;
}

export interface ActionKillSwitchUpdateV1 {
  enabled: boolean;
  reason?: string;
}

export interface ActionKillSwitchListResponseV1 {
  killSwitches: ActionKillSwitchV1[];
}

export interface ActionKillSwitchResponseV1 {
  killSwitch: ActionKillSwitchV1;
}
